---
#  __  __       _ _   _ ____  _                        ____                  _            
# |  \/  |_   _| | |_(_)  _ \| | __ _ _   _  ___ _ __ / ___|___  _   _ _ __ | |_ ___ _ __ 
# | |\/| | | | | | __| | |_) | |/ _` | | | |/ _ \ '__| |   / _ \| | | | '_ \| __/ _ \ '__|
# | |  | | |_| | | |_| |  __/| | (_| | |_| |  __/ |  | |__| (_) | |_| | | | | ||  __/ |   
# |_|  |_|\__,_|_|\__|_|_|   |_|\__,_|\__, |\___|_|   \____\___/ \__,_|_| |_|\__\___|_|   
#                                     |___/                                                
#                                                                                          
#Config Main of MultiPlayerCounter
#Time in seconds
update-players-interval: 30

#Format: "ip:port"
servers-to-query:
- "127.0.0.1:19133"
- "127.0.0.1:19134"
...